package model.queries;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 23:33:34 CDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class HrEmployeesImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public HrEmployeesImpl() {
    }
}

