package model.service.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Aug 10 23:34:38 CDT 2018
// ---------------------------------------------------------------------
public interface HrAppModule extends ApplicationModule {
    byte[] getHrReport(String deptId);

    byte[] getXMLDataHr(String deptId);
}

